
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 31 19:52:16 CST 2018
//----------------------------------------------------

package com.language.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 16;
  public static final int KEEP = 11;
  public static final int RPAREN = 24;
  public static final int THEN = 19;
  public static final int CALL = 22;
  public static final int REDUCED = 28;
  public static final int POSSTART = 21;
  public static final int IDENTIFIER = 29;
  public static final int AGGREGATE = 27;
  public static final int LPAREN = 23;
  public static final int POS = 10;
  public static final int ID = 15;
  public static final int PUT = 9;
  public static final int KEND = 13;
  public static final int NUMBER = 30;
  public static final int EOF = 0;
  public static final int WHEN = 18;
  public static final int SET = 3;
  public static final int ADD = 4;
  public static final int WHEND = 20;
  public static final int FEND = 17;
  public static final int error = 1;
  public static final int CHANGEDIR = 6;
  public static final int HIGH = 8;
  public static final int ASSIGN = 26;
  public static final int PUNTOCOMA = 25;
  public static final int FOR = 14;
  public static final int VAR = 2;
  public static final int LESS = 5;
  public static final int PLACE = 7;
  public static final int SKIP = 12;
}

