
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 17 11:30:17 CST 2018
//----------------------------------------------------

package com.language.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHEN = 19;
  public static final int POS = 12;
  public static final int REDUCED = 30;
  public static final int PUT = 10;
  public static final int HIGH = 9;
  public static final int PLACE = 7;
  public static final int LPAREN = 25;
  public static final int PUNTOCOMA = 27;
  public static final int LESS = 5;
  public static final int FOR = 16;
  public static final int RPAREN = 26;
  public static final int BLOCK = 8;
  public static final int AGGREGATE = 29;
  public static final int CALL = 24;
  public static final int BEGIN = 36;
  public static final int ASSIGN = 28;
  public static final int KEEP = 13;
  public static final int EndPROC = 39;
  public static final int ID = 17;
  public static final int LEFT = 32;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 31;
  public static final int LIGHT = 11;
  public static final int ADD = 4;
  public static final int FEND = 18;
  public static final int NUMBER = 41;
  public static final int WHEND = 20;
  public static final int KEND = 15;
  public static final int TIMES = 22;
  public static final int SAME = 35;
  public static final int SKIP = 14;
  public static final int THEN = 23;
  public static final int END = 37;
  public static final int PROC = 38;
  public static final int POSSTART = 21;
  public static final int BACK = 34;
  public static final int CHANGEDIR = 6;
  public static final int RIGHT = 33;
  public static final int VAR = 2;
  public static final int SET = 3;
  public static final int IDENTIFIER = 40;
}

